esphome:
  name: abfall

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi: !include secrets.yaml

  # Enable fallback hotspot (captive portal) in case wifi connection fails
captive_portal:

globals:
  - id: lampe
    type: bool
    initial_value: 'false'
  - id: button
    type: bool
    initial_value: 'false'


time:
  - platform: homeassistant
    id: zeit
    on_time:
      - seconds: 45
        minutes: 57
        hours: 11
        then:
          - globals.set:
              id: lampe
              value: 'false'
          - globals.set:
              id: button
              value: 'false'
          - light.turn_on:
              id: abfallneo
              brightness: 100%
              red: 1
              blue: 1
              green: 1
          - delay: 1s    
          - light.turn_off:
              id: abfallneo
      - seconds: 0
        minutes: /5
        then:
          - if:
              condition:
                light.is_off: abfallneo
              then:
                - light.turn_on:
                    id: abfallneo
                    brightness: 100%
                - delay: 3s    
                - light.turn_off:
                    id: abfallneo
      - seconds: 30
        minutes: /1
        then:
          - lambda: |-
              int lz;
              int lza;
              int lzb;
              int lzg;
              int lzr;
              static int colR;
              static int colG;
              static int colB;
              ESP_LOGD("HUL1", "Tick mit Lampe %d und Button %d", id(lampe), id(button));
              lza = (id(abfallnxta).state * 24) + (24 - id(zeit).now().hour);
              lzb = (id(abfallnxtb).state * 24) + (24 - id(zeit).now().hour);
              lzg = (id(abfallnxtg).state * 24) + (24 - id(zeit).now().hour);
              lzr = (id(abfallnxtr).state * 24) + (24 - id(zeit).now().hour);
              ESP_LOGD("HUL1", "a: %d; b: %d; g: %d; r: %d", lza, lzb, lzg, lzr);
              lz = 0;
              if (lza > 12 and lza < 37) {
                  ESP_LOGD("HUL1", "choice A");
                  colR = 0;
                  colG = 0;
                  colB = 1;
                  lz = lza;
                  id(lampe) = true;
              }
              if (lzb > 12 and lzb < 37) {
                  ESP_LOGD("HUL1", "choice B");
                  colR = 0;
                  colG = 1;
                  colB = 0;
                  lz = lzb;
                  id(lampe) = true;
              }
              if (lzg > 12 and lzg < 37) {
                  ESP_LOGD("HUL1", "choice G");
                  colR = 0;
                  colG = 1;
                  colB = 1;
                  lz = lzg;
                  id(lampe) = true;
              }
              if (lzr > 12 and lzr < 37) {
                  ESP_LOGD("HUL1", "choice R");
                  colR = 1;
                  colG = 0;
                  colB = 0;
                  lz = lzr;
                  id(lampe) = true;
              }
              if ((lza == lzb) or (lza == lzg) or (lza == lzr) or (lzb == lzg) or (lzb == lzr) or (lzg == lzr)) {
                  ESP_LOGD("HUL1", "choice multi");
                  colR = 1;
                  colG = 1;
                  colB = 1;
              }
              if (id(lampe) and !id(button)) {
                  ESP_LOGD("HUL1", "Lampe an %d", lz);
                  auto call = id(abfallneo).turn_on();
                  call.set_rgb(colR, colG, colB);
                  switch (lz) {
                    case 0 : call.set_effect("scan"); break; // jetzt sind wir im "gemerkten" Tag. wird aber durch WCS bereits erledigt.
                    case 13 ... 18 : call.set_effect("scan"); break; 
                    case 19 ... 28 : call.set_effect("pulse"); break;
                    case 29 ... 36 : call.set_effect("none"); break;
                    default : call.set_effect("strobe");  // darf eigentlich nicht passieren!
                  }
                  call.perform();
              } else {
                  ESP_LOGD("HUL1", "Lampe aus %d", lz);
                  auto call = id(abfallneo).turn_off();
                  call.perform();
              }


sun:
  latitude: 51.14°
  longitude: 9.414°

binary_sensor:
  - platform: gpio
    pin:
      number: D3
      mode:
        input: true
        pullup: true
    name: "button"
    on_press:
      then:
        - logger.log: "button pressed"
        - globals.set:
            id: button
            value: 'true'
        - light.turn_off:
            id: abfallneo

sensor:
  - platform: homeassistant
    id: abfallnxta
    internal: true
    entity_id: sensor.abfallnxta
  - platform: homeassistant
    id: abfallnxtb
    internal: true
    entity_id: sensor.abfallnxtb
  - platform: homeassistant
    id: abfallnxtg
    internal: true
    entity_id: sensor.abfallnxtg
  - platform: homeassistant
    id: abfallnxtr
    internal: true
    entity_id: sensor.abfallnxtr

light:
  - platform: neopixelbus
    type: GRB
    variant: WS2812
    pin: D6
    num_leds: 8
    name: "Abfall NeoPix"
    id: abfallneo
    effects:
      - random:
      - pulse:
      - strobe:
      - flicker:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:
      - addressable_flicker:
