esp8266:
  board: d1_mini
  framework:
    version: recommended
    
    
esphome:
  name: abfall
  on_boot:
    then:
      - light.turn_on:
          id: abfallneo
          effect: color wipe
          brightness: 100%

# Enable logging
logger:

# Enable Home Assistant API
#
# Achtung: Für Offlinekalender muss der API-Reboot auf 0s gesetzt werden, da die Tonne sonst alle 15 Minuten neu startet.
#

wifi:
  networks:
  - ssid: !secret GKssid
    password: !secret GKpassword
  - ssid: !secret BGssid
    password: !secret BGpassword
  - ssid: !secret SSssid
    password: !secret SSpassword
  ap:
    ssid: !secret FBssid
    password: !secret FBpassword
  on_connect:
    - light.turn_on:
        id: abfallneo
        effect: rainbow
        brightness: 100%
    - logger.log: "WiFi connected"
        

  # Enable fallback hotspot (captive portal) in case wifi connection fails
captive_portal:
#  keep_user_credentials: true  # option nicht aktiv.

ota:
  - platform: esphome

api:
  reboot_timeout: 60min
  password: ""
  on_client_connected:
    - light.turn_off:
        id: abfallneo
    - logger.log: "API connected"

globals:
  - id: lampe
    type: bool
    initial_value: 'false'
  - id: button
    type: bool
    initial_value: 'false'
    
time:
  - platform: sntp
    id: zeit
    on_time:
      - seconds: 45
        minutes: 57
        hours: 11
        then:
          - globals.set:
              id: lampe
              value: 'false'
          - globals.set:
              id: button
              value: 'false'
          - light.turn_on:
              id: abfallneo
              brightness: 100%
              red: 1
              blue: 1
              green: 1
          - delay: 1s    
          - light.turn_off:
              id: abfallneo
      - seconds: 0
        minutes: /5
        hours: 6-22
        then:
          - if:
              condition:
                light.is_off: abfallneo
              then:
              - if:
                  condition:
                    wifi.connected:
                  then:
                  - if:
                      condition:
                        api.connected:
                      then:
                        - light.turn_on:
                            id: abfallneo
                            effect: none
                            brightness: 100%
                            red: 0
                            blue: 0
                            green: 1
                      else:
                        - light.turn_on:
                            id: abfallneo
                            effect: none
                            brightness: 100%
                            red: 0
                            blue: 1
                            green: 0
                  else:
                    - light.turn_on:
                        id: abfallneo
                        effect: none
                        brightness: 100%
                        red: 1
                        blue: 0
                        green: 0
      - seconds: 3
        minutes: /5
        then:
          - lambda: |-
              // Mittags am Vortag geht die Lampe an.
              // Achtung: Für Offlinekalender muss der API-Reboot auf 0s gesetzt werden, da die Tonne sonst alle 15 Minuten neu startet.
              //
              // Hier werden die Daten für den Offlinekalender hinterlegt.
              // Es gibt nur 4 Abfuhrtypen:
              // A = Altpapier = Blau, Sensorname: abfallnxta
              // B = Biotonne = Grün, Sensorname: abfallnxtb
              // G = Gelbe Tonne = Gelb, Sensorname: abfallnxtg
              // R = Restmüll = Rot, Sensorname: abfallnxtr
              // MaxAbfDatum sind die Zahl der Abfuhrtermine plus 8 für 4 führende und 4 endende Termine.
              // intAbfDatum enthält die Abfuhrtermine mit 4 mal 0 führend und 4 mal 99999999 endend. Achtung: Immer den Tag vor dem Abfuhrtermin, damit das abziehen von "heute" klappt.
              // chrAbfType enthält die Abfuhrtypen zu den Terminen, mit allen 4 Typen einmal führend und einmal endend.
              // Daten Fuldabrück 2023
              //int MaxAbfDatum = 78 + 8; // + 8 für Header und Trailer 
              //int intAbfDatum[MaxAbfDatum] = {0, 0, 0, 0, 20230301, 20230302, 20230307, 20230309, 20230315, 20230316, 20230323, 20230329, 20230330, 20230403, 20230405, 20230412, 20230414, 20230420, 20230426, 20230427, 20230503, 20230505, 20230510, 20230511, 20230519, 20230524, 20230525, 20230531, 20230602, 20230608, 20230609, 20230615, 20230621, 20230622, 20230627, 20230629, 20230705, 20230706, 20230713, 20230719, 20230720, 20230725, 20230727, 20230802, 20230803, 20230810, 20230816, 20230817, 20230822, 20230824, 20230830, 20230831, 20230907, 20230913, 20230914, 20230919, 20230921, 20230927, 20230928, 20231006, 20231011, 20231012, 20231017, 20231019, 20231025, 20231026, 20231102, 20231108, 20231109, 20231114, 20231116, 20231122, 20231123, 20231130, 20231206, 20231207, 20231212, 20231214, 20231220, 20231221, 20231229, 99999999, 99999999, 99999999, 99999999};
              //char chrAbfType[] = "ABGRGBARGBRGBARGBRGBARGBRGBARGBRGBARGBRGBARGBRGBARGBRGBARGBRGBARGBRGBARGBRGBARGBRABGR"; //Vorne und hinten ABGR anhängen!!
              // Daten Felsberg 2023
              int MaxAbfDatum = 175 + 8; // + 8 für Header und Trailer 
              int intAbfDatum[MaxAbfDatum] = {0, 0, 0, 0, 20260118, 20260119, 20260120, 20260120, 20260125, 20260126, 20260126, 20260202, 20260202, 20260208, 20260209, 20260209, 20260210, 20260210, 20260210, 20260215, 20260216, 20260222, 20260223, 20260223, 20260227, 20260302, 20260302, 20260303, 20260303, 20260308, 20260309, 20260309, 20260310, 20260315, 20260316, 20260322, 20260323, 20260323, 20260324, 20260324, 20260329, 20260329, 20260406, 20260407, 20260407, 20260408, 20260412, 20260413, 20260414, 20260414, 20260419, 20260420, 20260420, 20260427, 20260427, 20260504, 20260505, 20260505, 20260506, 20260506, 20260506, 20260507, 20260510, 20260511, 20260517, 20260518, 20260518, 20260526, 20260526, 20260526, 20260527, 20260531, 20260601, 20260601, 20260602, 20260607, 20260608, 20260614, 20260615, 20260615, 20260616, 20260616, 20260622, 20260622, 20260628, 20260629, 20260629, 20260630, 20260705, 20260706, 20260707, 20260707, 20260712, 20260713, 20260713, 20260720, 20260720, 20260726, 20260727, 20260727, 20260728, 20260728, 20260728, 20260802, 20260803, 20260809, 20260810, 20260810, 20260817, 20260817, 20260818, 20260818, 20260823, 20260824, 20260824, 20260825, 20260830, 20260831, 20260906, 20260907, 20260907, 20260908, 20260908, 20260915, 20260915, 20260920, 20260921, 20260921, 20260922, 20260927, 20260928, 20260929, 20260929, 20261004, 20261005, 20261005, 20261012, 20261012, 20261018, 20261019, 20261019, 20261020, 20261020, 20261020, 20261025, 20261026, 20261101, 20261102, 20261102, 20261104, 20261106, 20261109, 20261109, 20261110, 20261110, 20261115, 20261116, 20261116, 20261117, 20261122, 20261123, 20261129, 20261130, 20261130, 20261201, 20261201, 20261207, 20261207, 20261213, 20261214, 20261214, 20261215, 20261218, 20261220, 20261221, 20261221, 20261227, 20261228, 20261228, 99999999, 99999999, 99999999, 99999999};
              char chrAbfType[] = "ABGRARRRBRRRRBRRGRRARBRRARRRRBRRGARBRRRRRRBRRGARRRBRRRRBRRGRRSARBRRRRRRBRRGARBRRRRRRBRRGARRRBRRRRBRRGRRARBRRRRRRBRRGARBRRRRRRBRRGARRRBRRRRBRRGRRARBRRSARRRRBRRGARBRRRRRRBRRGARRRBRRABGR"; //Vorne und hinten ABGR anhängen!!
              int heute;
              int lz;
              int lza = 0;
              int lzb = 0;
              int lzg = 0;
              int lzr = 0;
              static int colR;
              static int colG;
              static int colB;
              ESP_LOGD("HUL1", "Tick mit Lampe %d und Button %d", id(lampe), id(button));
              heute = id(zeit).now().year * 10000 + id(zeit).now().month * 100 + id(zeit).now().day_of_month;  
              ESP_LOGD("HUL1", "Zeit %d", heute);
              ESP_LOGD("HUL1", "Sensor %f", (id(abfallnxta).state * 24) + (24 - id(zeit).now().hour));
              // Zum testen der Offlinefunktion reicht es die Sensoren aus Homeassistant umzubenennen, dann greift das System auf die Offlinedaten, da die Sensoren dann nan sind.
              if ((id(statussensor).state) and !isnan(id(abfallnxta).state)) { 
                  ESP_LOGD("HUL2", "Online");
                  lza = (id(abfallnxta).state * 24) + (24 - id(zeit).now().hour);
                  lzb = (id(abfallnxtb).state * 24) + (24 - id(zeit).now().hour);
                  lzg = (id(abfallnxtg).state * 24) + (24 - id(zeit).now().hour);
                  lzr = (id(abfallnxtr).state * 24) + (24 - id(zeit).now().hour);
              } else {
                  ESP_LOGD("HUL2", "Offline oder nan");
                  for (int i = 0; i<MaxAbfDatum; i++) {
                      if (intAbfDatum[i] >= heute ){
                          switch (chrAbfType[i]) {
                              // +1, da wir den einen Tag den wir in Excel abgezogen haben ja wieder draufrechnen müssen.
                              case 'A':
                                  if (lza == 0) lza = ((intAbfDatum[i] - heute + 1) * 24) + (24 - id(zeit).now().hour);
                              break;
                              case 'B':
                                  if (lzb == 0) lzb = ((intAbfDatum[i] - heute + 1) * 24) + (24 - id(zeit).now().hour);
                              break;
                              case 'G':
                                  if (lzg == 0) lzg = ((intAbfDatum[i] - heute + 1) * 24) + (24 - id(zeit).now().hour);
                              break;
                              case 'R':
                                  if (lzr == 0) lzr = ((intAbfDatum[i] - heute + 1) * 24) + (24 - id(zeit).now().hour);
                              break;
                          }
                      }
                  }
              }              
              
              ESP_LOGD("HUL1", "a: %d; b: %d; g: %d; r: %d", lza, lzb, lzg, lzr);
              lz = 0;
              if (lza > 12 and lza < 37) {
                  ESP_LOGD("HUL1", "choice A");
                  colR = 0;
                  colG = 0;
                  colB = 1;
                  lz = lza;
                  id(lampe) = true;
              }
              if (lzb > 12 and lzb < 37) {
                  ESP_LOGD("HUL1", "choice B");
                  colR = 0;
                  colG = 1;
                  colB = 0;
                  lz = lzb;
                  id(lampe) = true;
              }
              if (lzg > 12 and lzg < 37) {
                  ESP_LOGD("HUL1", "choice G");
                  colR = 1;
                  colG = 1;
                  colB = 0;
                  lz = lzg;
                  id(lampe) = true;
              }
              if (lzr > 12 and lzr < 37) {
                  ESP_LOGD("HUL1", "choice R");
                  colR = 1;
                  colG = 0;
                  colB = 0;
                  lz = lzr;
                  id(lampe) = true;
              }
              if ((lza == lzb) or (lza == lzg) or (lza == lzr) or (lzb == lzg) or (lzb == lzr) or (lzg == lzr)) {
                  ESP_LOGD("HUL1", "choice multi");
                  colR = 1;
                  colG = 1;
                  colB = 1;
              }
              if (id(lampe) and !id(button)) {
                  ESP_LOGD("HUL1", "Lampe an %d", lz);
                  auto call = id(abfallneo).turn_on();
                  call.set_rgb(colR, colG, colB);
                  switch (lz) {
                    case 0 : call.set_effect("scan"); break; // jetzt sind wir im "gemerkten" Tag. wird aber durch WCS bereits erledigt.
                    case 13 ... 18 : call.set_effect("scan"); break; 
                    case 19 ... 28 : call.set_effect("pulse"); break;
                    case 29 ... 36 : call.set_effect("none"); break;
                    default : call.set_effect("strobe");  // darf eigentlich nicht passieren!
                  }
                  call.perform();
              } else {
                  ESP_LOGD("HUL1", "Lampe aus %d", lz);
                  auto call = id(abfallneo).turn_off();
                  call.perform();
              }


sun:
  latitude: 51.14°
  longitude: 9.414°

binary_sensor:
  - platform: gpio
    pin:
      number: D3
      mode:
        input: true
        pullup: true
    name: "button"
    internal: true
    on_press:
      then:
        - logger.log: "button pressed"
        - globals.set:
            id: button
            value: 'true'
        - light.turn_off:
            id: abfallneo
  - platform: status
    name: "Statussensor"
    id: statussensor


sensor:
  - platform: homeassistant
    id: abfallnxta
    internal: true
    entity_id: sensor.abfallnxta
  - platform: homeassistant
    id: abfallnxtb
    internal: true
    entity_id: sensor.abfallnxtb
  - platform: homeassistant
    id: abfallnxtg
    internal: true
    entity_id: sensor.abfallnxtg
  - platform: homeassistant
    id: abfallnxtr
    internal: true
    entity_id: sensor.abfallnxtr

light:
  - platform: neopixelbus
    type: GRB
    variant: WS2812
    pin: D6
    num_leds: 8
    name: "Abfall NeoPix"
    id: abfallneo
    effects:
      - random:
      - pulse:
      - strobe:
      - flicker:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:
      - addressable_flicker:


