esphome:
  name: test

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi: !include secrets.yaml

  # Enable fallback hotspot (captive portal) in case wifi connection fails
captive_portal:


time:
  - platform: sntp
    id: zeit
    on_time:
      - seconds: 0
        minutes: /1
#        hours: *
        then:
          - lambda: |-
              int lz;
              ESP_LOGD("HUL2", "Zeit %d", id(zeit).now());


binary_sensor:
  - platform: gpio
    pin:
      number: D3
      mode:
        input: true
        pullup: true
    name: "button"
    on_press:
      then:
        - logger.log: "button pressed"

light:
  - platform: neopixelbus
    type: GRB
    variant: WS2812
    pin: D6
    num_leds: 3
    name: "Test NeoPix"
    id: testneo
    effects:
      - random:
      - pulse:
      - strobe:
      - flicker:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:
      - addressable_flicker:


